# -*- coding: utf-8 -*-
"""final event.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_9LmHcr8xbiABHfIGkFyXFOnNqYMiuS
"""

# Imports
import gradio as gr
from PIL import Image, ImageDraw

# 🖼️ FINAL INVITATION IMAGE GENERATOR
def generate_invitation_image(event_type, theme, gifts):

    # Create background
    img = Image.new("RGB", (800, 500), color=(255, 192, 203))  # pink background
    draw = ImageDraw.Draw(img)

    # Title
    draw.rectangle([0, 0, 800, 80], fill=(255, 105, 180))
    draw.text((250, 25), "INVITATION", fill="white")

    # Event Name
    draw.text((200, 120), f"Event: {event_type}", fill="black")

    # Theme
    draw.text((200, 180), f"Theme: {theme}", fill="black")

    # Gifts
    draw.text((200, 240), f"Gifts: {gifts}", fill="black")

    # Decorative shapes
    draw.ellipse((50, 350, 150, 450), fill="yellow")
    draw.ellipse((650, 350, 750, 450), fill="blue")

    return img

# UI
with gr.Blocks() as app:
    gr.Markdown("# 🎉 AI Invitation Image Generator")

    event = gr.Textbox(label="Event Type (Birthday, Wedding)")
    theme = gr.Textbox(label="Theme (Pink Princess, Royal, etc)")
    gifts = gr.Textbox(label="Gift Ideas (Cake, Flowers, Chocolates)")

    output = gr.Image(label="Generated Invitation Image")

    btn = gr.Button("Generate Invitation Image")
    btn.click(generate_invitation_image, [event, theme, gifts], output)

app.launch(share=True)